{% set name = "py3dep" %}
{% set version = "0.17.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/py3dep-{{ version }}.tar.gz
  sha256: a0e284980fa5ade3fa61b0a1ded119d4ef526e2ce492aa5b96c630094db6a35d

build:
  entry_points:
    - py3dep = py3dep.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling >=1.12
    - hatch-vcs
    - pip
  run:
    - python >=3.9
    - async-retriever <0.18,>=0.17
    - click >=0.7
    - cytoolz
    - geopandas-base >=0.10
    - pyogrio
    - numpy >=1.21
    - pygeoogc <0.18,>=0.17
    - pygeoutils <0.18,>=0.17
    - rasterio >=1.2
    - rioxarray >=0.11
    - scipy
    - shapely >=2
    - xarray >=2023.01

test:
  imports:
    - py3dep
  commands:
    - pip check
    - py3dep --help
  requires:
    - pip

about:
  home: https://github.com/hyriver/py3dep
  summary: Access topography data at any resolution via 3DEP web service of USGS.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
