{% set name = "py3dep" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/py3dep-{{ version }}.tar.gz
  sha256: 079af5295bb610fcfef0b245f33050dd1ba8788cbdee9ffefec066358421da83

build:
  entry_points:
    - py3dep = py3dep.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - setuptools-scm >=7
    - pip
  run:
    - python >=3.8
    - async-retriever <0.16,>=0.15
    - click >=0.7
    - cytoolz
    - geopandas >=0.10
    - numpy >=1.21
    - pygeoogc <0.16,>=0.15
    - pygeoutils <0.16,>=0.15
    - rasterio >=1.2
    - rioxarray >=0.11
    - scipy
    - shapely >=1.8.5
    - xarray >=2023.04

test:
  imports:
    - py3dep
  commands:
    - pip check
    - py3dep --help
  requires:
    - pip

about:
  home: https://github.com/hyriver/py3dep
  summary: Access topography data at any resolution via 3DEP web service of USGS.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
