{% set name = "py3dep" %}
{% set version = "0.13.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/py3dep-{{ version }}.tar.gz
  sha256: 4e80ac07758d64c202a4fcbd7c688398edff6e4bf31660b7b7022930fee31d7b

build:
  number: 0
  noarch: python
  entry_points:
    - py3dep = py3dep.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - async_retriever >=0.3.2
    - click >=7.0
    - cytoolz
    - numpy >=1.17
    - pygeoogc >=0.13.2
    - pygeoutils >=0.13.2
    - python >=3.8
    - rasterio >=1.2
    - rioxarray >=0.10
    - scipy
    - shapely >=1.7
    - xarray >=0.18

test:
  imports:
    - py3dep
  commands:
    - pip check
    - py3dep --help
  requires:
    - pip

about:
  home: https://github.com/cheginit/py3dep
  summary: Access USGS 3DEP database and get data such as elevation in the US
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
