{% set name = "py3dep" %}
{% set version = "0.11.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/py3dep-{{ version }}.tar.gz
  sha256: 813cd3cb6c6852ddce85aeab902be1112b11ea406d9da17e764f8aeb118446e4

build:
  number: 0
  noarch: python
  entry_points:
    - py3dep = py3dep.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - async_retriever >=0.2
    - click
    - cytoolz
    - numpy >=1.17
    - pydantic
    - pygeoogc >=0.11
    - pygeoutils >=0.11.5
    - python >=3.7
    - rasterio >=1.2
    - scipy
    - shapely >=1.6
    - xarray >=0.17

test:
  imports:
    - py3dep
  commands:
    - pip check
    - py3dep --help
  requires:
    - pip

about:
  home: https://github.com/cheginit/py3dep
  summary: Access USGS 3DEP database and get data such as elevation in the US
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
