{% set name = "py3dep" %}
{% set version = "0.13.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/py3dep-{{ version }}.tar.gz
  sha256: 8814c5091f7744a745812e1c0e128c853f88484467f971524a005f92d2e4ac4a

build:
  entry_points:
    - py3dep = py3dep.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools-scm
  run:
    - python >=3.8
    - async-retriever >=0.3.12
    - click >=0.7
    - cytoolz
    - geopandas >=0.10
    - numpy >=1.21
    - pygeoogc >=0.13.12
    - pygeoutils >=0.13.12
    - rasterio >=1.2
    - rioxarray >=0.11
    - scipy
    - shapely >=1.8
    - xarray >=2022.03.0

test:
  imports:
    - py3dep
  commands:
    - pip check
    - py3dep --help
  requires:
    - pip

about:
  home: https://github.com/hyriver/py3dep
  summary: Access topography data at any resolution via 3DEP web service of USGS.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
