{% set name = "py3dep" %}
{% set version = "0.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/py3dep-{{ version }}.tar.gz
  sha256: 526a5899834c9b4618f6b98b2a05dac9f2b4eb3ea21f0f980ffac04f27560f35

build:
  number: 0
  noarch: python
  entry_points:
    - py3dep = py3dep.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - click
    - cytoolz
    - numpy
    - pygeoogc
    - pygeoutils
    - python >=3.7
    - rasterio
    - shapely
    - xarray

test:
  imports:
    - py3dep
  commands:
    - pip check
    - py3dep --help
  requires:
    - pip

about:
  home: https://github.com/cheginit/py3dep
  summary: Access USGS 3DEP database and get data such as elevation in the US
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
