{% set name = "py3dep" %}
{% set version = "0.10.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/py3dep-{{ version }}.tar.gz
  sha256: 518945dbc6605052c8bd3ebd48c3e54a550bff4a4c991a31ab76915dd91afdf4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - aiodns
    - aiohttp
    - brotlipy
    - chardet
    - cytoolz
    - defusedxml
    - geopandas
    - nest-asyncio
    - netcdf4
    - orjson
    - owslib
    - pygeoogc
    - pygeoutils
    - pyproj
    - python >=3.6
    - rasterio
    - requests
    - setuptools
    - shapely
    - simplejson
    - xarray

test:
  imports:
    - py3dep
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cheginit/py3dep
  summary: Access USGS 3DEP database and get data such as elevation in the US
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
