{% set name = "py3dep" %}
{% set version = "0.12.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/py3dep-{{ version }}.tar.gz
  sha256: 5705495fef3326c61ebd314e3c4b309a395101ccadd3f1f0656986b148d75746

build:
  number: 0
  noarch: python
  entry_points:
    - py3dep = py3dep.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - async_retriever >=0.3
    - click
    - cytoolz
    - numpy >=1.17
    - pydantic
    - pygeoogc >=0.12
    - pygeoutils >=0.12
    - python >=3.7
    - rasterio >=1.2
    - rioxarray >=0.8
    - scipy
    - shapely >=1.6
    - xarray >=0.18
    - importlib_metadata

test:
  imports:
    - py3dep
  commands:
    - pip check
    - py3dep --help
  requires:
    - pip

about:
  home: https://github.com/cheginit/py3dep
  summary: Access USGS 3DEP database and get data such as elevation in the US
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
